import { Router } from 'express';
import authRouter from '../modules/auth/auth.routes';
import usersRouter from '../modules/users/users.routes';
import patientsRouter from '../modules/patients/patients.routes';
import doctorsRouter from '../modules/doctors/doctors.routes';
import healthWorkersRouter from '../modules/healthWorkers/healthWorkers.routes';
import appointmentsRouter from '../modules/appointments/appointments.routes';
import availabilityRouter from '../modules/availability/availability.routes';
import consultationsRouter from '../modules/consultations/consultations.routes';
import triageRouter from '../modules/triage/triage.routes';
import hospitalsRouter from '../modules/hospitals/hospitals.routes';
import consentRouter from '../modules/consent/consent.routes';
import privacyRouter from '../modules/privacy/privacy.routes';
import referralsRouter from '../modules/referrals/referrals.routes';
import followupsRouter from '../modules/followups/followups.routes';
import notificationsRouter from '../modules/notifications/notifications.routes';
import auditRouter from '../modules/audit/audit.routes';
import aiProxyRouter from '../modules/ai/aiProxy.routes';
import adminRouter from '../modules/admin/admin.routes';
import storageRouter from '../modules/storage/storage.routes';
import keysRouter from '../modules/keys/keys.routes';
import syncRouter from '../modules/sync/sync.routes';
import workspaceRouter from '../modules/workspace/workspace.routes';

const v1 = Router();

v1.use('/auth', authRouter);
v1.use('/users', usersRouter);
v1.use('/patients', patientsRouter);
v1.use('/doctors', doctorsRouter);
v1.use('/health-workers', healthWorkersRouter);
v1.use('/appointments', appointmentsRouter);
v1.use('/availability', availabilityRouter);
v1.use('/consultations', consultationsRouter);
v1.use('/triage', triageRouter);
v1.use('/hospitals', hospitalsRouter);
v1.use('/consent', consentRouter);
v1.use('/privacy', privacyRouter);
v1.use('/referrals', referralsRouter);
v1.use('/followups', followupsRouter);
v1.use('/notifications', notificationsRouter);
v1.use('/audit', auditRouter);
v1.use('/admin', adminRouter);
v1.use('/storage', storageRouter);
v1.use('/keys', keysRouter);
v1.use('/sync', syncRouter);
v1.use(workspaceRouter);
v1.use(aiProxyRouter);

export default v1;
